name: build

on:
  push:
    branches:
      - master
        
  pull_request:
    types: [opened, synchronize]
  

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup | Xcode 11.3
      run: sudo xcode-select --switch /Applications/Xcode_11.3.app
    - name: Run tests
      run: swift test -v
